### ISSUE TITLE
Wix-Style-React compatibility

### ISSUE THREAD

**Issue by LeonidLevi** [wix/stylable-components#184]
Let's discuss here how far we go for compatibility with wix-style-react.

Let's do it on a case-by-case basis.

Currently we have 2 questions:
1. wix-style-react has a slider with an arbitrary amount of knobs (1 to infinity), but we only see sliders with just 1 or 2 knobs on the internet. Do we want to allow any number of knobs just for compatibility?
2. Wix-style-react’s time input has a very specific look. We want a different look for our time input that will not necessarily be compatible. Do we make our look, or wix-style-react’s?

**Comment by idoros** [comment]
I don't think this should be discussed in this context. `stylable-components` is a generic component library and we can't be effected by decisions in a wix specific library. 

If we find any use case, api, design decision in `wix-style-react` or any other library interesting, then we can discuss adopting it. I wouldn't put this specific lib assome role-model.

More specifically about the question raised:
1. I have no problem with extending the slider API to support multi nodes. several examples of components that could benefit from this: `gradient-input`, `timeline-input`...
2. I'm not sure what is the incompatibility of the design you are referring to.

**Comment by arnonkehat** [comment]
1. How much more complicated is the API for multiple nodes?
2. More details.
