### ISSUE TITLE
Time Picker Component (bugs / improvements / questions)

### ISSUE THREAD

**Issue by maksymc** [wix/stylable-components#192]
Hi there, 

Here is the list of issues/improvements that I've found:

# DESKTOP
## IMPROVEMENTS
- [x] Time picker should be circular. When a user reaches 23:59 we should move to 00:59 (on Arrow Up). Right now we disable stepper and forbade to move forward.

- [x] Set "cursor: pointer" for am / pm. Or do it any other way;) The idea is that when you hover over input, we display "text" cursor when we hover over "am/pm" we need to show pointer.

- [x] When the focus is on 'am / pm' user should be able to switch between values by typing am / pm via the keyboard. 
e.g if current value 'am' I should be able to type 'pm' and it will change value accordingly. 

## BUGS
- [x] am / pm should gain focus only when a user reaches it via "tab". By clicking on am / pm we should simply change it to the next value.
(see Wix Bookings for reference)

- [x] When I switch to Time Picker from another input (using TAB) both 'hh' & 'mm" gain focus.
http://joxi.ru/VrwNaDwcKoJ1DA

**Steps to reproduce:** 
1. select 1st time picker component (Current Time)
2. move to 2nd component (controlled 24 time format) using TAB

- [x] Highlight am / pm on hover. 
See [Wix Style React](https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=TimeInput&full=0&down=0&left=1&panelRight=0) for reference.

- [x] Disables state design is wrong (Safari). 
See [basic input in Zepplin](https://zpl.io/agGkPRa) for reference. 

- [x] No Value input works wrong on focus. When user focuses on the input (Mouse or TAB), here is what we see - http://joxi.ru/xAe6lwjTYMBYKr
No value input should set the focus for both digits in 'hh' OR 'mm', exactly like in other cases. 

- [x] Placeholder should disappear from the input on focus. Here is what happens now (http://joxi.ru/Q2KGd36I9ORv42), here is what I expect to see (http://joxi.ru/nAyo3DwhX95wqm)
NOTE: when user focused on empty input we show default time. So numbers might differ from the screenshot I've provided. 

- [x] "Page Up" & "Page Down" are not working. 
NOTE: according to the spec Page Up/Down should work only for 'mm'

- [x] Issue in logic that automatically moves focus from 'hh' to 'mm'. 

**Steps to reproduce:**
1. Set "controlled 24 time format" input to 01:55.
2. Focus on 'hh'
3. Try to type 12 in 'hh' section (NOTE: you need to type it, do not use Stepper)

**Actual result:**
No good. Input moves you to 'mm'. 'hh' is set to 01.

**Expected result:**
12 is entered into 'hh'.

- [x] "No Value" input -> type 2 into both 'hh' & 'mm'.
Here is what I see - http://joxi.ru/V2VEkJXu0BeDjm
I expect to see 02:02

- [x] Focus for 'hh' & 'mm" works incorrectly.

**Steps to reproduce:**
1. focus on 'hh' (focus appears over 2 digits representing hours)
2. double-tap on focused 'hh'

**Actual result:**
focus disappears, a cursor is placed in between 2 digits & the user can not enter anything there (with keyboard)

**Expected result:**
nothing happens. 'hh' preserve focus state

- [x] Focus looks bad in FF - http://joxi.ru/p27vejxc0L6zGm

- [x] Stepper is not shown in FF (might be relevant to issues 👆) - http://joxi.ru/p27vejxc0L6zGm

## QUESTIONS / CLARIFICATIONS
- [x] Is this the correct format - http://joxi.ru/v29oez1hG4Wbgr
Should it be 15:07? Just curious. 

# MOBILE

## IMPROVEMENTS
- [ ] "Clear" is not working on iOS
"Clear" should set time to its default value

## QUESTIONS / CLARIFICATIONS
- [x] Can we ignore am/pm prop on mobile and always display inputs in 24h format

> This is related to the fact that we can not set native time picker component to display am/pm

**Comment by maksymc** [comment]
A new list of issues/improvements:

# DESKTOP
## IMPROVEMENTS

- [ ] Logic:
1. Time is set to "11:59". When user increases 'mm' by one -> time picker should show 12:00
('mm' -> set to min, 'hh' add 1h) 
2. Time is set to "11:59 am". When user increases 'mm' by one -> time picker should show "12:00 pm". 
('mm' -> set to min, 'hh' add 1h, 'am' change to 'pm')

- [ ] Set default time to be 12:00 (00:00 is not supported by 12h format and is not the best behavior)

##BUGS

- [ ] Placeholder: when I focus on placeholder input, 'am' is not horizontally aligned with 'hh' & 'mm'.
http://joxi.ru/vAWv1qxckRK3W2
NOTE: same thing is for disabled input

- [ ] Unclickable area in the input: there is a relatively big unclickable area inside the picker (http://joxi.ru/KAgd9DzTgOeeVr). 
I expect that when I click inside this red area focus will be set to 'hh'.   

- [ ] fn/ctrl + stepper UP/DOWN is not working as expected. 
Expected is to increase/decrease by 10. 

- [ ] 'hh' can be set to show 1 value (http://joxi.ru/eAOGaxKI4GEXJA)
**Steps:**
1. Focus on 'hh'
2. Type 1 with keyboard
3. Hit "Tab" button
**Actual result:**
Input displays 1:XX
http://joxi.ru/eAOGaxKI4GEXJA
**Expected result**
Input displays 01:XX
http://joxi.ru/Q2KGd36I9gXZy2

- [ ] FF: border-color is not applied on hover

- [ ] FF: hover looks different for 'mm' and 'am/pm'
http://joxi.ru/1A5ve0ncKwkaXr
http://joxi.ru/brRGOyRIQ8VPam

- [ ] FF: am/pm is not displaying in all inputs
http://joxi.ru/EA4jeGOCD0Zgym

- [ ] IE: focus shows for both 'mm' & 'am/pm'
http://joxi.ru/EA4jeGOCD0Zdwm


# MOBILE
## BUGS

- [ ] Time Picker looks bad on iOS
http://joxi.ru/Y2LBLOWUnvLGGr

- [ ] "Clear" is not working on Android

**Comment by tyv** [comment]
> fn/ctrl + stepper UP/DOWN

maybe `shift`?
