### ISSUE TITLE
Slider: list of issues

### ISSUE THREAD

**Issue by maksymc** [wix/stylable-components#217]
Hi there, 

Below you can find the list of bugs, questions, improvements:

# DESKTOP
## IMPROVEMENTS

- [x] Focus: focus should be shown only when a user focuses on slider via TAB button. 
If I interact with slider via the mouse -> do not show focus for the handle. 
If I interacted with slider via mouse & then changed value with the keyboard -> do not show focus for the handle.
If I focused to slider via TAB button, show focus & do not hide it until I move to another control/element.

## BUGS

- [x] Slider with tooltip: value changes/applies on mouse release. Other components change/apply value on mouse press.

- [x] Accessibility: `aria-orientation` is set to `horizontal` for all all sliders (including vertical)
http://joxi.ru/823EeM3u6wzb4r

- [x] Keyboard behavior: shift + UP/DOWN arrow key should not increase/decrease value by 10. It was replaced with Page UP/DOWN
See [master spec](https://github.com/wix/stylable-components/blob/master/specs/slider/Spec.md#input-methods) for reference.

- [x] Keyboard behavior: keyboard behavior is inconsistent in different browsers. 
E.g. shift + UP/DOWN arrow key sets value to Min/Max in FF & changes value by 10 in Chrome. 
Please double-check behavior in browsers. 
NOTE: shift +UP/DOWN/LEFT/RIGHT should not have special behavior. All special things are covered with CTRL/FN buttons. 

- [x] User can change the value for 2 sliders at the same time:
**Steps:**
1. Press on handle for any slider (press & hold. Do not release mouse)
2. While holding the mouse hit "TAB" button
**Actual result:**
Focus is on the next slider (you can change values via keyboard) PLUS mouse still holds the handle for the first slider, so you can change values for 2 sliders
**Expected result:**
Focus preserves on the current slider. User can move focus to the next slider/element only when the mouse is released. 
**NOTE:**
This is a trivial issue. If it takes a lot of time to fix, simply ignore it. 

# MOBILE
## BUGS

- [x] Slider with error state: ::progressBar color changes from red to blue when I select/drag the handle.
(reproduces on both iOS & Android)

**Comment by Ta4i** [comment]
Finished
