### ISSUE TITLE
Dropdown component :: misspelling in the elements images

### ISSUE THREAD

**Issue by abumami** [wix/stylable-components#220]
**Popoup (wrong) ==> Popup (correct)**

![dropdown-elements-misspelling](https://user-images.githubusercontent.com/2210136/29565977-c45205d2-8750-11e7-9ed5-0e22d2b288b7.png)

![dropdown-multi-elements-misspelling](https://user-images.githubusercontent.com/2210136/29566054-1813f6e4-8751-11e7-84e4-da3dc2a17934.png)

**Comment by giladgrush** [comment]
![popup2](https://user-images.githubusercontent.com/19182511/29867395-1b993048-8d84-11e7-8a71-b72a88fb6408.png)
![popup1](https://user-images.githubusercontent.com/19182511/29867396-1b9fcd68-8d84-11e7-93ec-a1dd468b791b.png)

Here you go
