### ISSUE TITLE
TimePicker improvements

### ISSUE THREAD

**Issue by wtfil** [wix/stylable-components#240]
* [x] Time is set to "11:59". When user increases 'mm' by one -> time picker should show 12:00
('mm' -> set to min, 'hh' add 1h)
Time is set to "11:59 am". When user increases 'mm' by one -> time picker should show "12:00 pm".
('mm' -> set to min, 'hh' add 1h, 'am' change to 'pm')
* [x] Page Up (shift + up arrow key/stepper up) -> increase 'mm' value by 10 (works only for 'mm')
* [x] Page Down (shift + down arrow key/stepper down) -> decrese 'mm' value by 10 (works only for 'mm')
* [ ]  "Clear" is not working on Android
* [x] Unclickable area in the input: there is a relatively big unclickable area inside the picker (http://joxi.ru/KAgd9DzTgOeeVr).
I expect that when I click inside this red area focus will be set to 'hh'.

**Comment by maksymc** [comment]
## BUGS
**Desktop**
- [ ] Stepper arrow disappears.
**steps**
1. Focus on the first time picker (Current time "read-only");
2. Set focus to 'hh';
3. Increase 'hh' value with stepper UP arrow (use mouse)
4. Move mouse to DOWN arrow key (do not press, just move cursor down)
**actual**
UP arrow button is missed - http://joxi.ru/Y2LBLOWUnvBl9r
**expected**
Both UP & DOWN buttons should be visible

- [ ] inconsisteny in focus.
According to spec, when user hits UP/DOWN stepper button, we automatically set focus on 'hh'. 
Now focus is not set + in different inputs different values change (it can be 'hh', 'mm' or 'am/pm')
From what I see it works badly with inputs that you've interacted previously. It remembers last focused element and changes it.
