### ISSUE TITLE
TimePicker in Edge has cropped 0

### ISSUE THREAD

**Issue by urik9** [wix/stylable-components#284]
**Steps to reproduce:**

1. Open the demo in edge
2. Go to the  @time picker
3. Input several numbers in order (works well if you have numbers that make no sense as time like (99:99) 

**Result:**
The minutes are cropped 

![screen shot 2017-09-06 at 5 37 25 pm](https://user-images.githubusercontent.com/5908902/30117848-1abae292-932a-11e7-920a-817abb7aeb61.png)
@wtfil Please contact me if you have any questions

Thanks

**Comment by wtfil** [comment]
@urik9 Hi, thank you for issue!
Can you pls check it once again? Yesterday I made some changes in styles, and now I can't see any bug in edge 15 and edge 14.
Tested with browserstack

**Comment by tyv** [comment]
@urik9 ping

**Comment by wtfil** [comment]
fixed
