### ISSUE TITLE
NumberInput component

### ISSUE THREAD

**Issue by LeonidLevi** [wix/stylable-components#31]
Create a NumberInput component.

It will have a custom / stylable stepper.

The stylable API will look something like this:
```
NumberInput {
 /* style the root element - typically the border and the background will be styled */
}

NumberInput::stepper {
 /* style the stepper buttons (both of them) */
}

NumberInput::errorMessage {
/* style for error message wrapper node */
}
```

the `::stepper` subelement is an internal component (`<Stepper>?` and it has its own ::upButton (or ::upIcon?) and ::downButton (or ::downIcon?) subelements, for more detailed styling)

States to style:
```
:hover
:focus
:disabled
:error  /* for erroneous user input */
```
Props:
//regular props for the component... let's see what they are
`errorMessage="<node or text>"` - ability to pass a react component to display on error. what would be the correct name? Can also be text
`prefix="<node>"`
`suffix="<node>"`

reference for some obscure props that might be needed:
https://github.com/wix/wix-style-react/tree/master/src/Input

Keyboard / Touch handling - need to make sure we have all the proper stuff
Accessibility - needs to be mostly ARIA compliant. What needs to be done?

Full Spec:
https://github.com/wix/stylable-components/tree/volodymyrk/31-number-input/specs/NumberInput

**Comment by VKobeliatsky** [comment]
@LeonidLevi @tyv can we close this since the component is merged?
