### ISSUE TITLE
Slider component

### ISSUE THREAD

**Issue by maksymc** [wix/stylable-components#32]
Create a Slider component.

You can find all the relevant info in the git documentation. 

Links to documentation:
README file - https://github.com/wix/stylable-components/blob/master/specs/slider/README.md
Spec file - https://github.com/wix/stylable-components/blob/master/specs/slider/Spec.md

**Comment by maksymc** [comment]
Here is the link to git documentation - https://github.com/wix/wix-react-components

Also, I got a great note from Arnon: "to make sure that value and default value are an array of numbers and not a number"
We need this to be able to implement slider with 2 knobs (select range) in future.

**Comment by maksymc** [comment]
Link to design assets - https://zpl.io/2kRTvO

**Comment by Ta4i** [comment]
Slider merged to Master
