### ISSUE TITLE
CheckBox

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable-components#332]
**Stylesheet:**
- Hardcoded colors. Should use project.st.css variables.
- Icons customized via props. Should use `background-image` with `url()` pointing to a local svg asset. See [comp best practices guide](https://wix.github.io/stylable/docs/guides/stylable-component-best-practices#keep-svg-and-images-overridable).

**Props:**
Comp uses a native input, so no need for a default `tabIndex: 0`. It's already focuable by default.

**Comment by idoros** [comment]
dup #352
