### ISSUE TITLE
number-input overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#353]
## docs
- [x] onChange signature is wrong
- [x] RTL should be removed (as it delivered using context and not props)
~~- [ ] add an optional prop multipleOf enforces the input value to be a multiple of this number~~

## implementation
- [x] missing properties decorator 

## style
- [x] kebab-cased classnames should be camelCased

**Comment by maksymc** [comment]
@nadavwix 

As for the: 
> add an optional prop multipleOf enforces the input value to be a multiple of this number

I've discussed this with Leo, Yuriy and the rest of the team. We all agree that the input itself should not handle things like this. Such manipulations should be the responsibility of a higher order component. In any case, we will not be able to cover all cases/needs BUT we can keep the API simple & clean. 

Let me know if you have any other concerns.
