### ISSUE TITLE
slider overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#354]
## docs
- [x] onChange signature is incorrect
- [x] change displayMarks to displayStopMarks
- [x] remove rtl it has been moved to context
- [x] remove error? seems to be just an arbitrary state that can be added from above
- [x] progressMarks and marks can be implemented using a background image in repeat according to step value 

## implemention
- [x] change
```
export const AXISES: {[name: string]: AxisOptions} = {
    x: 'x',
    y: 'y',
    xReverse: 'x-reverse',
    yReverse: 'y-reverse'
};
```
   to 
```
export const AXES = {
    x: 'x',
    y: 'y',
    xReverse: 'x-reverse',
    yReverse: 'y-reverse'
};
```
   the map type means theres no completion for fields
- [x] remove RTL it has been moved to context
- [x] what does required mean in a slider?
- [ ] relativeStep, isVertical, isReverse do not belong in state as they are all derived
- [x] change dirrection to direction
- [x] change "SLIDER-NATIVE-INPUT" automation id to NATIVE_INPUT

## style 
- [x] camelCase class names and states

**Comment by tyv** [comment]
@maksymc take a look

**Comment by abumami** [comment]
AXISES is not a word. AXES is the plural of the singular AXIS.

**Comment by maksymc** [comment]
Hey,
Will take a look and update spec / readme accordingly. 
Will not be able to process it until tomorrow though.

**Comment by maksymc** [comment]
@nadavwix please see my comments:
 
1. "marks" & "progressMarks" can be implemented with bg image but I do not like this idea. 
BG image is hard to style. And if you want a bg image you can always write:

::marks {
background: transparent;
background-image: url("gradient_bg.png");
}

2. As for the "what does required mean in a slider?"
Slider can be a form element. Sicne all form components have "required" prop, we decided to keep in in slider as well.

**Comment by maksymc** [comment]
@abumami please rename the "slider.md" to "slider-spec.md" according to this [doc](https://github.com/wixplosives/stylable-components-guide/blob/master/project/folder-structure.md#docs)

**Comment by abumami** [comment]
@maksymc 
The spec file is strictly a developers' file. This is a file that is created and maintained by a developer for the development team. It would be more correct for you to rename.

**Comment by maksymc** [comment]
ok, will do it after the merge.

**Comment by maksymc** [comment]
Removing "extract to theme" item since it is going to be implemented by Yuriy & Leo separately.

**Comment by wtfil** [comment]
@nadavwix what do you mean by?
 
> relativeStep,  isVertical, isReverse do not belong in state as they are all derived

**Comment by nadavwix** [comment]
@wtfil these states are all computed from properties, they dont need to be stored as state.

it'll make the code simpler and somewhat more performant

**Comment by wtfil** [comment]
@nadavwix I see the point. I guess the main motivation for this was to avoid the same calculation over and over again.
I will disagree that this make any significant impact on performance (i consider that this actually will be slightly faster since calculation made just in live circles)
And I disagree that `isVertical(this.props.axis)` is more readable that `this.state.isVertical`.
The only downside of this is to have like two sources of truth

**Comment by maksymc** [comment]
@nadavwix what do you say regarding the latest comment from Fil? Can we close this ticket?

**Comment by maksymc** [comment]
Closing this ticket.
