### ISSUE TITLE
toggle overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#355]
## docs 
- [x] onChange signature is incorrect

## implementation
- [x] remove switch-wrap div
- [x] missing properties decorator
- [x] change "TOGGLE-INPUT" automation id to NATIVE_INPUT

## styles
- [x] camelCase class names and variables
- [x] nativeInput class should be nativeInput
- [x] not checked is mistakenly similar to disabled

**Comment by wtfil** [comment]
@nadavov 
doc is fixed #357

`switch-wrap` is needed to simplify css
instead of 
```css
transform: translateX(calc(value(width) - value(padding) * 2 - value(borderWidth) * 2 - 100%))
```
we have
```css
 margin-left: 100%;
 transform: translateX(-100%);
```
see #226 for full update
classNames fixed #358

**Comment by idoros** [comment]
@wtfil 

**doc**- need to fix signature in docs props as well
**switch-wrap** - can we flatten it into root? - if not then this part is missing in the style portion of the readme and spec

**Comment by wtfil** [comment]
@idoros what kind of prop do you mean? All off them are meat the requirements ([docs](https://github.com/wix/stylable-components/tree/master/docs/toggle#props))

`switch-wrap` could not be the root. I did not include this in doc, since it does not have any value for user, all user need is `root` and `switch`

**Comment by idoros** [comment]
I meant specifically `onChange` that currently has the type `func` and should be `{value:number}` or eventually ChangeEvent<number>.

I'm missing something about the `switch-wrap`. there are only 2 elements in the Toggle root: 
1. nativeInput which is not part of the layout (absolute and hidden)
2. the switch itself. 
why do you need the wrap at all? switch should work the same relative to root

**Comment by wtfil** [comment]
@idoros here is the logic and responsibilities:
1) `switch` - has the size (ie `width` and `height`)
2) `root` - should respect `switch` height but also has own padding and width
3) `switch-wrap` has the width and height of `root`. needed to avoid explicit numbers in transitions

**Comment by wtfil** [comment]
@idoros `onChange` signature is updated in doc

**Comment by idoros** [comment]
still can't see the need, just tried removing it and it acts the same, adding padding or width to root looks fine:
![image](https://user-images.githubusercontent.com/574751/30806945-792a413a-a200-11e7-8893-3cad4eb0b02a.png)

Changing height has no effect on the switch symbol itself.

**Comment by wtfil** [comment]
@idoros sorry, you are right. I just deleted and realized that it works the same

**Comment by wtfil** [comment]
@idoros removed in #375

**Comment by wtfil** [comment]
@idoros what do you mean by "not checked is mistakenly similar to disabled" ?
![image](https://user-images.githubusercontent.com/1421128/30850207-75677ce0-a2ad-11e7-8f8f-b1e1c9e16c00.png)

**Comment by wtfil** [comment]
@idoros who can assist me with theming of component?

**Comment by wtfil** [comment]
@idoros ping

**Comment by idoros** [comment]
Off mode alone looks disabled, is this our design? There is a design rule in wix not to have grey looking ui for enabled interactive ui.

@leo?

**Comment by maksymc** [comment]
@idoros yes, this is our design. 
You can see it here - https://zpl.io/VYJpGna. 

@oleksiik-uxd please take a look and decide if we need to do some adjustments.

**Comment by maksymc** [comment]
@nadavwix @idoros I am removing "extract to theme" item from this ticket and all the rest of the tickets. 
Leo & Yuri are going to handle theming for components separately.
