### ISSUE TITLE
time-picker overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#364]
## docs
- [x] remove rtl, should be implemented using context
- [x] enum  ('ampm’, '24hr’)  change to "ampm" | "24hr" this is a valid TS syntax for enum and more readable
- [x] children should be separated to prefix and suffix props
- [x] keyboard behavior is unclear in spec and missing delete/bkspace
- [x] RTL behavior is missing

## implementation
- [x] missing properties decorator
~~- [ ] AM/PM button should not switch sides in RTL mode~~
- [x] rtl should be implemented via context
- [x] change AMPM enum to "AM" | "PM" typings format
- [x] segment data should be removed from state as it is derived from props
- [x] native input support should be replaced with mobile detection per guidlines
this should support mocking in tests

## style
- [x] change camel case classNames

## tests
- [x] entering "5" into mm input and entering "7" into mm input seems oddly repitative.
- [x] most describes in this file should be "it"s 
- [x] tests should say what they test and not what the test does.

**Comment by maksymc** [comment]
"AM/PM button should not switch sides in RTL mode"

It should. Most of the resources that we've checked do that:
~ Booking.com
~ http://demos.telerik.com/kendo-ui/timepicker/right-to-left-support
~ native <input type="time"> in Chrome & FF (version 57)

**Comment by maksymc** [comment]
"keyboard behavior is unclear in spec and missing delete/bkspace"

1. Added delete/bkspace behavior
2. As for "keyboard behavior is unclear" I am not sure what exactly is wrong. yes, it is complex but 70% of stuff is taken from w3 aria specs, so it should be pretty clear. 
Let me know if there is anything specific that is hard for you to understand.

**Comment by wtfil** [comment]
@nadavov all tests for timepicker has beed refactored at https://github.com/wix/stylable-components/pull/466/files
No more copy/paste and better tests titles

**Comment by maksymc** [comment]
> segment data should be removed from state as it is derived from props

According to Fill this item is no longer relevant. Marking as done & closing the ticket.
