### ISSUE TITLE
stepper overview

### ISSUE THREAD

**Issue by nadavwix** [wix/stylable-components#370]
## docs
- [x] separate from number input, as it is used in more places

## implementation
- [x] icons to stylable SVG
- [x] missing properties decorator

## styles
- [x] camelCase class names
- [x] extract to theme
- [x] flex is overkill here, better use absolute positioning with percentages

**Comment by VKobeliatsky** [comment]
@nadavwix, could you please elaborate on what exactly has to be extracted to theme?

**Comment by nadavwix** [comment]
@VKobeliatsky  remove it for now

**Comment by maksymc** [comment]
"separate from number input, as it is used in more places" - working on a separate REAMDE for the stepper. Closing this ticket.
