### ISSUE TITLE
add tslint

### ISSUE THREAD

**Issue by tyv** [wix/stylable-components#38]
we're about to add `tslint` with rules we used in style editor
they could be quite unlike by a lot of people, but we believe that we should use one tslint config for all projects (we will put then that config as package).

I would love if we all could agree on one set and then put in separate package and use and maintain widely and together. 

cc @AviVahl @tobich

**Comment by AviVahl** [comment]
I know little about tslint presets out there.
I saw @tyv mentioning Microsoft's...
Did you mean: https://github.com/Microsoft/tslint-microsoft-contrib ?

**Comment by tyv** [comment]
@AviVahl we used on top of microsoft contrib with few arguable amends https://github.com/wixplosives/style-editor-components/blob/17fbfaba7509f9a47b1b21defce2749b48d8e912/tslint.json

I want to use smth like that.
but I can accept else setup, we can use clean microsoft contrib or airbnb port for tslint

**Comment by tyv** [comment]
we're got agreement
1. we create package that will bring `tslint` and `tslintconf` and linting scripts to any package
2. by default it will extend with nothing this https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js
3. in case if someone want to add/change rule there should be a voting process, with that rules:
  + it goes active for 5 working days.
  + we're voting with reactions `+1` or `-1` on pull request with changed/added rules or in main issue description with proposal.
  + we announce that fact in team Slack channel, after that we're calculating 5 days.

**Comment by tyv** [comment]
closed via #140
