### ISSUE TITLE
Sauce Labs - Configure to run for every travis build

### ISSUE THREAD

**Issue by JoMarton** [wix/stylable-components#80]
The issue we had with sauce labs is that the badge and browser matrix would update for every build and not only for master. 
To avoid it we disabled it unless the branch is master and is not a PR. 

I would really like to be aware of failing tests in all platforms BEFORE I merge to master...

**Comment by AviVahl** [comment]
Yes, I too would like to see cross platform tests in pull requests.

@AlexShemeshWix any thoughts on how we can get the badge of the README only for master runs, while allowing branches to still be cross-browser tested?

**Comment by AlexShemeshWix** [comment]
Ive being thinking something like that
https://github.com/exogen/badge-matrix#travisuserreposaucesauceuser
Its not working good but the idea is to parse build results from sauce labs
and filter out builds that match some query parameter.
 https://github.com/exogen/badge-matrix/issues/10

Kind of complicated, but can be done.
Browser stack also works but it does not have browser matrix badge. And
they dont have latest versions for mobile platforms.

Both solutions feel little bit unstable. Some browsers would not not start
randomly.
Ive talked to Wix Automation, they say Selenium Grid is inherently
unstable, so for pull requests they use Firefox/Chrome on Linux only.

Will update when i know more.

**Comment by JoMarton** [comment]
Another unnecessarily complicated solution in sauce labs is to have a sub-account for master and sub-account for the rest.. 

Anyhow, currently my vote is to have sauce labs running for all PRs and have the badge unreliable than the opposite....

**Comment by giladgrush** [comment]
@JoMarton Please close if done

**Comment by AviVahl** [comment]
It was done a long time ago.
