### ISSUE TITLE
slider component needs ARIA information

### ISSUE THREAD

**Issue by abumami** [wix/stylable-components#99]
See [slider aria info](https://www.w3.org/TR/wai-aria-practices/#slider)

**Comment by giladgrush** [comment]
Please close if done

**Comment by maksymc** [comment]
We have Aria for both [Slider](https://github.com/wix/stylable-components/blob/master/specs/slider/Spec.md#accessibility) & [Range Slider](https://github.com/wix/stylable-components/blob/3e77221cae1d9045d2e269a36896ca84e8c0400b/specs/rangeslider/Spec.md#accessibility)

**Comment by maksymc** [comment]
Closing
